//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KadyrovInstituteISP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string GroupID { get; set; }
        public string Kafedra { get; set; }
        public Nullable<int> StudyCourseID { get; set; }
    
        public virtual StudyCourse StudyCourse { get; set; }
    }
}
